{
 "title": "Performance Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total packed bottles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    COUNT(*) AS \"Total\"\r\nFROM (\r\n    SELECT DISTINCT entity_id, time_index, stage\r\n    FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n    WHERE $__timeFilter(time_index)\r\n        AND stage = 'HANDOVER_READY'\r\n) final_count;\r\n"
    }
   ]
  },
  {
   "title": "Pack bottle average duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    AVG(duration_seconds)::bigint AS \"Average Duration\"\r\nFROM (\r\n    SELECT \r\n        (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\n    FROM (\r\n        SELECT\r\n            time_index AS time_index1,\r\n            LEAD(time_index, 10) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n            stage AS stage1,\r\n            LEAD(stage, 10) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n        FROM (\r\n            SELECT DISTINCT entity_id, time_index, stage\r\n            FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n            WHERE $__timeFilter(time_index)\r\n            ORDER BY time_index ASC\r\n        ) unique_rows\r\n    ) sub\r\n    WHERE stage1 = 'ACTIVE' \r\n      AND stage2 = 'HANDOVER_READY'\r\n      AND stage1 <> stage2\r\n      AND time_index2 IS NOT NULL\r\n) final_sub;\r\n"
    }
   ]
  },
  {
   "title": "Unfinished executions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    (SELECT COUNT(DISTINCT CONCAT(entity_id, stage, time_index)) \r\n     FROM \"mtopeniot\".\"ettaskpackbottle\" \r\n     WHERE $__timeFilter(time_index) AND stage = 'DETECT_READY') \r\n    - \r\n    (SELECT COUNT(DISTINCT CONCAT(entity_id, stage, time_index)) \r\n     FROM \"mtopeniot\".\"ettaskpackbottle\" \r\n     WHERE $__timeFilter(time_index) AND stage = 'HANDOVER_READY') \r\nAS \"Difference\";"
    }
   ]
  },
  {
   "title": "Unsuccessful detections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    COUNT(*) AS \"Total\"\r\nFROM (\r\n    SELECT \r\n        time_index1\r\n    FROM (\r\n        SELECT\r\n            time_index AS time_index1,\r\n            LEAD(time_index, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n            stage AS stage1,\r\n            LEAD(stage, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n        FROM (\r\n            SELECT DISTINCT entity_id, time_index, stage\r\n            FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n            WHERE $__timeFilter(time_index)\r\n            ORDER BY time_index ASC\r\n        ) unique_rows\r\n    ) sub\r\n    WHERE stage1 = 'ACTIVE' \r\n      AND stage2 <> 'DETECT_READY'\r\n      AND stage1 <> stage2\r\n      AND time_index2 IS NOT NULL\r\n) final_count;\r\n"
    }
   ]
  },
  {
   "title": "Pick average duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    AVG(duration_seconds)::bigint AS \"Average Duration\"\r\nFROM (\r\n    SELECT \r\n        (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\n    FROM (\r\n        SELECT\r\n            time_index AS time_index1,\r\n            LEAD(time_index, 1) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n            stage AS stage1,\r\n            LEAD(stage, 1) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n        FROM (\r\n            SELECT DISTINCT entity_id, time_index, stage\r\n            FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n            WHERE $__timeFilter(time_index)\r\n            ORDER BY time_index ASC\r\n        ) unique_rows\r\n    ) sub\r\n    WHERE stage1 = 'DETECT_READY' \r\n      AND stage2 = 'PICK_READY'\r\n      AND stage1 <> stage2\r\n      AND time_index2 IS NOT NULL\r\n) final_sub;\r\n"
    }
   ]
  },
  {
   "title": "Fill average duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    AVG(duration_seconds)::bigint AS \"Average Duration\"\r\nFROM (\r\n    SELECT \r\n        (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\n    FROM (\r\n        SELECT\r\n            time_index AS time_index1,\r\n            LEAD(time_index, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n            stage AS stage1,\r\n            LEAD(stage, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n        FROM (\r\n            SELECT DISTINCT entity_id, time_index, stage\r\n            FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n            WHERE $__timeFilter(time_index)\r\n            ORDER BY time_index ASC\r\n        ) unique_rows\r\n    ) sub\r\n    WHERE stage1 = 'PICK_READY' \r\n      AND stage2 = 'FILL_READY'\r\n      AND stage1 <> stage2\r\n      AND time_index2 IS NOT NULL\r\n) final_sub;\r\n"
    }
   ]
  },
  {
   "title": "Cap average duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    AVG(duration_seconds)::bigint AS \"Average Duration\"\r\nFROM (\r\n    SELECT \r\n        (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\n    FROM (\r\n        SELECT\r\n            time_index AS time_index1,\r\n            LEAD(time_index, 3) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n            stage AS stage1,\r\n            LEAD(stage, 3) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n        FROM (\r\n            SELECT DISTINCT entity_id, time_index, stage\r\n            FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n            WHERE $__timeFilter(time_index)\r\n            ORDER BY time_index ASC\r\n        ) unique_rows\r\n    ) sub\r\n    WHERE stage1 = 'FILL_READY' \r\n      AND stage2 = 'CAP_READY'\r\n      AND stage1 <> stage2\r\n      AND time_index2 IS NOT NULL\r\n) final_sub;\r\n"
    }
   ]
  },
  {
   "title": "Handover average duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    AVG(duration_seconds)::bigint AS \"Average Duration\"\r\nFROM (\r\n    SELECT \r\n        (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\n    FROM (\r\n        SELECT\r\n            time_index AS time_index1,\r\n            LEAD(time_index, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n            stage AS stage1,\r\n            LEAD(stage, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n        FROM (\r\n            SELECT DISTINCT entity_id, time_index, stage\r\n            FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n            WHERE $__timeFilter(time_index)\r\n            ORDER BY time_index ASC\r\n        ) unique_rows\r\n    ) sub\r\n    WHERE stage1 = 'CAP_READY' \r\n      AND stage2 = 'HANDOVER_READY'\r\n      AND stage1 <> stage2\r\n      AND time_index2 IS NOT NULL\r\n) final_sub;\r\n"
    }
   ]
  },
  {
   "title": "Stages Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT DISTINCT time_index, stage\r\nFROM \"mtopeniot\".\"ettaskpackbottle\"\r\nWHERE stage IN ('IDLE', 'ACTIVE', 'DETECT_READY', 'PICK_READY', 'FILL_READY', 'CAP_READY')\r\n  AND $__timeFilter(time_index)\r\nORDER BY time_index ASC;"
    }
   ]
  },
  {
   "title": "Pack bottle total duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    time_index1,\r\n    (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\nFROM (\r\n    SELECT\r\n        time_index AS time_index1,\r\n        LEAD(time_index, 10) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n        stage AS stage1,\r\n        LEAD(stage, 10) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n    FROM (\r\n        SELECT DISTINCT entity_id, time_index, stage\r\n        FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n        WHERE $__timeFilter(time_index)\r\n        ORDER BY time_index ASC\r\n    ) unique_rows\r\n) sub\r\nWHERE stage1 = 'ACTIVE' \r\n  AND stage2 = 'HANDOVER_READY'\r\n  AND stage1 <> stage2\r\n  AND time_index2 IS NOT NULL\r\nORDER BY time_index1 ASC;"
    }
   ]
  },
  {
   "title": "Bottle detection duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    time_index1,\r\n    (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\nFROM (\r\n    SELECT\r\n        time_index AS time_index1,\r\n        LEAD(time_index, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n        stage AS stage1,\r\n        LEAD(stage, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n    FROM (\r\n        SELECT DISTINCT entity_id, time_index, stage\r\n        FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n        WHERE $__timeFilter(time_index)\r\n        ORDER BY time_index ASC\r\n    ) unique_rows\r\n) sub\r\nWHERE stage1 = 'ACTIVE' \r\n  AND stage2 = 'DETECT_READY'\r\n  AND stage1 <> stage2\r\n  AND time_index2 IS NOT NULL\r\nORDER BY time_index1 ASC;"
    }
   ]
  },
  {
   "title": "Pick duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    time_index1,\r\n    (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\nFROM (\r\n    SELECT\r\n        time_index AS time_index1,\r\n        LEAD(time_index, 1) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n        stage AS stage1,\r\n        LEAD(stage, 1) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n    FROM (\r\n        SELECT DISTINCT entity_id, time_index, stage\r\n        FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n        WHERE $__timeFilter(time_index)\r\n        ORDER BY time_index ASC\r\n    ) unique_rows\r\n) sub\r\nWHERE stage1 = 'DETECT_READY' \r\n  AND stage2 = 'PICK_READY'\r\n  AND stage1 <> stage2\r\n  AND time_index2 IS NOT NULL\r\nORDER BY time_index1 ASC;"
    }
   ]
  },
  {
   "title": "Fill duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    time_index1,\r\n    (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\nFROM (\r\n    SELECT\r\n        time_index AS time_index1,\r\n        LEAD(time_index, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n        stage AS stage1,\r\n        LEAD(stage, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n    FROM (\r\n        SELECT DISTINCT entity_id, time_index, stage\r\n        FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n        WHERE $__timeFilter(time_index)\r\n        ORDER BY time_index ASC\r\n    ) unique_rows\r\n) sub\r\nWHERE stage1 = 'PICK_READY' \r\n  AND stage2 = 'FILL_READY'\r\n  AND stage1 <> stage2\r\n  AND time_index2 IS NOT NULL\r\nORDER BY time_index1 ASC;"
    }
   ]
  },
  {
   "title": "Cap duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    time_index1,\r\n    (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\nFROM (\r\n    SELECT\r\n        time_index AS time_index1,\r\n        LEAD(time_index, 3) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n        stage AS stage1,\r\n        LEAD(stage, 3) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n    FROM (\r\n        SELECT DISTINCT entity_id, time_index, stage\r\n        FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n        WHERE $__timeFilter(time_index)\r\n        ORDER BY time_index ASC\r\n    ) unique_rows\r\n) sub\r\nWHERE stage1 = 'FILL_READY' \r\n  AND stage2 = 'CAP_READY'\r\n  AND stage1 <> stage2\r\n  AND time_index2 IS NOT NULL\r\nORDER BY time_index1 ASC;"
    }
   ]
  },
  {
   "title": "Handover duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "dataset": "mtopeniot",
     "rawSql": "SELECT \r\n    time_index1,\r\n    (EXTRACT(EPOCH FROM (time_index2 - time_index1)))::bigint AS duration_seconds\r\nFROM (\r\n    SELECT\r\n        time_index AS time_index1,\r\n        LEAD(time_index, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS time_index2,\r\n        stage AS stage1,\r\n        LEAD(stage, 2) OVER (PARTITION BY entity_id ORDER BY time_index) AS stage2\r\n    FROM (\r\n        SELECT DISTINCT entity_id, time_index, stage\r\n        FROM \"mtopeniot\".\"ettaskpackbottle\"\r\n        WHERE $__timeFilter(time_index)\r\n        ORDER BY time_index ASC\r\n    ) unique_rows\r\n) sub\r\nWHERE stage1 = 'CAP_READY' \r\n  AND stage2 = 'HANDOVER_READY'\r\n  AND stage1 <> stage2\r\n  AND time_index2 IS NOT NULL\r\nORDER BY time_index1 ASC;"
    }
   ]
  }
 ]
}